### ISSUE TITLE
Example code does not work wth multiple clients

### ISSUE THREAD

**Issue by ynerant** [Haivision/srtgo#8] opened 2020-10-10 11:04 UTC
I slightly modified the code given in the README file to have multiple incoming sockets:

```golang
package main

import (
    "github.com/haivision/srtgo"
    "fmt"
)

func main() {
	options := make(map[string]string)
	options["transtype"] = "live"

	sck := srtgo.NewSrtSocket("0.0.0.0", 8090, options)
	sck.Listen(2)

	for {
		s, err := sck.Accept()
		if err != nil {
			fmt.Printf("Error while accepting SRT socket: %s\n", err)
			continue;
		}

		go func(s *srtgo.SrtSocket) {
			buff := make([]byte, 2048)
			for {
				n, _ := s.Read(buff, 10000)
				if n == 0 {
					break;
				}
				// fmt.Println("Received %d bytes", n)
			}
		}(s)
	}
}

```

Everything is OK while no client is connected. However, once one client is connected, the line `sck.Accept()` return always an error (but continues to accept real connections):

```bash
$ go run main.go
2020/10/10 12:53:22 Warning - Error setting option transtype to live
2020/10/10 12:53:29 Connection accepted!
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
Error while accepting SRT socket: srt accept, error accepting the connection
```

And so on (there are ~50000 errors per second).

Did I make something wrong? The expected behaviour is to have the line `srt.Accept()` that blocks the current goroutine avec return the connected socket once a client is connected, not to have everytime errors, and two gorountine are communicating with two different sockets.

I have srt v1.4.2 installed in my Arch Linux, but also tested with Alpine Linux using libsrt v1.4.2. I use the latest version of srtgo, released on the July 31st.

**Comment by cdavid14** [comment] 2020-10-21 10:41
@ynerant this library was made to be compatible with srt v1.4.1 , @jeoliva is working on the new version v1.4.2

**Comment by ravenium** [comment] 2020-10-27 22:47
@cdavid14 This appears to be happening even with 1.4.1 - admittedly my golang sockets are usually handled by higher level libraries, so I'm not 100% sure I'm doing it right either.  For example, it appears that it's ignoring any of my streamid options as well.

It might be helpful to version this a bit as between this and the new(ish) PR that adds a third return value to Accept(), it's really easy to break things. Are there any github projects you're aware of that utilize this?

**Comment by iSchluff** [comment] 2020-11-12 00:14
You can still handle multiple connections if you call ```Listen(1)```, however I don't really know what the side effects of the client number are.

**Comment by iSchluff** [comment] 2021-06-25 09:40
I think the problem is that ```options["blocking"]``` is not set. Setting it to any string should make the error go away.
I believe there may be an error at https://github.com/Haivision/srtgo/blob/765827cb33598e6bbba1f068dd0345e2f62612c0/srtgo.go#L104-L110

**Comment by jeoliva** [comment] 2021-07-06 12:09
Fixed by @iSchluff

**Closed by jeoliva** 2021-07-06 12:09 UTC
